// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrpjbvleknoyxdxwgznr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndycGpidmxla25veXhkeHdnem5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTc1NjYsImV4cCI6MjA1OTc5MzU2Nn0.Aj9zhgq_ZlTTC7KBHg879DCbHsmrLb46YfK84qRm59U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);